### PR TITLE
Italian Tranlsate

### PR DESCRIPTION
**Pull request by qw123wh**
Add Italian Translate

### CODE REVIEW

**Comment by roeiedri** [comment]
Thanks appreciate it

**Comment by roeiedri** [comment]
Ummm I just realized, what did u translate?
The Italian file have like 50% stuff that's not related to the default strings file

**Comment by qw123wh** [comment]
if not good tell me which is the correct file to translate.

**Comment by qw123wh** [comment]
As for the theme of the light currently the keys of the navbar remain white must be added

<item name = " android: windowLightNavigationBar " > true </ item >

**Comment by roeiedri** [comment]
https://github.com/Chooloo/call_manage/blob/master/app/src/main/res/values/strings/strings.xml
That's the file that needs to be translated
Btw what file did u translate?

**Comment by qw123wh** [comment]
https://github.com/Chooloo/call_manage/blob/master/app/src/main/res/values/strings.xml

this file has 205 lines, the one you sent me has 166 lines. This is more complete right? Translate this?

**Comment by roeiedri** [comment]
The one you translate has way more strings than needed, honestly I have no idea where they came from because a lot of them aren't even being used
So yeah the one I just sent is the one that should be translated

**Comment by qw123wh** [comment]
OK I translate what you sent me

**Comment by roeiedri** [comment]
No no sorry hhh all the strings file werent fully organized
Im organizing it and ill ping u in a bit

**Comment by qw123wh** [comment]
ok

**Comment by roeiedri** [comment]
https://github.com/Chooloo/call_manage/blob/master/app/src/main/res/values/strings.xml
Here that's the one, I needed to organize the strings files to different locale folders because I had both the folders AND different strings file in the default values folder
So now every language strings file is in a different values folder

**Pull request merged**
